coucou :)

ajouter : 

<ul>
<li>Fusion de plantes (anti doublon)</li>
<li>affecter facilement plusieurs plantes &agrave; un groupe (zone/lieu)</li>
</ul>

<?php if ((int) $_SESSION['utilisateur_id'] === 2) {
    echo PlantUrl::getApply(12) . '<br/>';
    echo PlantUrl::getApply(null) . '<br/>';
    echo PlantUrl::get('vegetable', 'list', ['k1' => 'v1', 'k2' => 'v2']) . '<br/>';
    echo $_SESSION['referrer'] ?? 'no_referrer';
    ?>
    <!--<input type="text" id="UserAgent" />-->
    <script>
        // alert("width = " + screen.width + "x" + screen.height
        //     + "\n DPR = " + window.devicePixelRatio
        //     + "\n userAgent = " + navigator.userAgent);
        // document.getElementById('UserAgent').value = navigator.userAgent;
    </script>
<?php } ?>
