<h1>Liste des Photos</h1>

<?php
if (is_array($this->photos)) { ?>
	<table  class="table">
		<thead>
			<tr><th></th></th><th>Plante</th><th>Action</th><th></th></tr>
		</thead>
		<tbody>
			<?php
			foreach ($this->photos as $photo) { ?>
				<tr>
					<td>
						<div class="w-100 text-center">
							<img src="<?= $photo->getThumbPath('H', 115) ?>" class='rounded' height="115px"/>
						</div>
					</td>
					<td>
						<?= isset($photo->vegetable) ? $photo->getVegetable()->getName() : '<span class="text-danger">SANS PLANTE</span>' ?>
					</td>
					<td>
						<?= isset($photo->action) ? $photo->getAction()->getTitle() . ' - ' . $photo->getAction()->getDate() : '' ?>
					</td>
					<td>
						<a href="<?= PlantUrl::getEdit($photo->getId()) ?>" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
					</td>
					<td>
						<?php
						$isDefault = $photo->vegetable !== null && $photo->getId() === $photo->getVegetable()->getDefaultPhoto()->getId();
						if (!$isDefault) {
						?>
							<a href="<?= PlantUrl::getDelete($photo->getId(), ['prevaction' => 'list']) ?>" onclick="return confirm('Voulez-vous vraiment supprimer cette photo ?')" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
						<?php } ?>
					</td>
				</tr>
			<?php
			} ?>
		</tbody>
	</table>
    <?php
    include BPCF_ROOT . '/view/pagination.phtml';
    ?>
<?php
}
else { ?>
	Pas encore de photo !
<?php
} ?>
