<h1><?= isset($this->entity->id) ? 'Modifier' : 'Créer' ?> un type</h1>

<form action="<?= PlantUrl::getApply($this->entity->getId()) ?>" method="POST" class="was-validated ">
	
	<div class="form-floating mb-3">
		<input type="text" class="form-control" id="name" name="name" placeholder="Nom" value="<?= $this->entity->getName() ?>" required>
		<label for="name">Nom</label>
	</div>
	<div class="form-floating mb-3">
		<select class="form-select" id="type" name="parent">
			<option value="">Sans parent</option>
			<?php
				foreach ($this->types as $type) {
					echo '<option value="' . $type->getId() . '" ' . ($this->entity->parent === $type->getId() ? 'selected' : '') . '>' . $type->getName() . '</option>';
				}
			?>
		</select>
		<label for="type">Type parent</label>
	</div>
	<button type="submit" class="btn btn-primary">Enregistrer</button>
</form>