<h1>Liste des types <a class="btn btn-outline-primary" href="<?= PlantUrl::getEdit() ?>" role="button">+</a></h1>

<?php
if (is_array($this->types)) { ?>
	<table  class="table">
		<thead>
			<tr><th>Nom</th><th>Parent</th></tr>
		</thead>
		<tbody>
			<?php
			foreach ($this->types as $type) { ?>
				<tr>
					<td>
						<a href="<?= PlantUrl::getView($type->getId()) ?>">
							<?= $type->getName() ?>
						</a>
					</td>
					<td>
						<?= $type->parent !== null ? $type->getParent()->getName() : '' ?>
					</td>
					<td>
						<a href="<?= PlantUrl::getEdit($type->getId()) ?>" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
					</td>
				</tr>
			<?php
			} ?>
		</tbody>
	</table>
<?php
}
else { ?>
	Pas encore de type de plante ! <a href="<?= PlantUrl::getEdit() ?>" >Créer un type de plante</a>
<?php
} ?>


